language: go

os:
  - linux
  - osx

script:
  - make test
  - make
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then make build_all; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then make release_all; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then make build_macos; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then make release_macos; fi

deploy:
  provider: releases
  file_glob: true
  file: dist/*
  skip_cleanup: true
  on:
    tags: true
  api-key:
    secure: cFxvYscwWKd2//UHQUxLNbmUvsixBxs7AWE29bhlQV8zjaHcfH1Pxjs1C1h8A50h/Gzp8X6Lcfikp3juPVBQ1ZKZqJlToRxP5RExkEsP/ogOG4R/Qxy2+oBUq5art3NUde2E7IcffDjhbK4AR0a+zHVZcc61ZwW+6hkjbAo7JEIG/huLb7duvW/FbN4xwj5QVdKaMeghrd8B+sMCrOtTQ0G6iaMrWHXd5Yf2AoFAeDuRna7BVzuOTcE72qZsXd4w4fwYvIAPRze95Hp3ELMNppoJi3PCzJdyVFii3lmhxLnKbLIR2Xfp/OCW2K9ZrLNoB9NuPjsMUhKCVgWpQAq+jZwRmFpWkCG8hSvWAp3DOSbU8o4Mj8AMTmPbdDuTk6HW5tGN/AQWVifOl0DPtHnRdwmXkJ0nd0geb/Az3GY9pGiikGrxMUy5VXpXLJnPOsoYUkyekdpoaUZ4K88vsOnPxEWOqkZD8jO3CMwatl0hS4WpJH2c7ZTPEuNvK8Z5l11RfOMV31yuFuJDAzksaH255RAAwjeMzL+p6tA/BFtpFT+y8+vz8H7qfSJUcbkzUXItD/bWXeYD/USwPA9aRi1cQEXCtNpxuMaY+tEP5gk/esyom6ORXHUleaOv4vIpgS6IT1TAyHmH9p6nL8OMKORR9NgnvDwz+bSPVDU1HdUqVLA=
